http:
  # debug release
  mode: 'debug'
  listen: 19999

mysql:
  host: '47.98.96.81:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'devops'
  username: 'luban-dev'
  password: 'EzEDJvEpzf0WH9QcW19Id'
