http:
  # debug release
  mode: 'debug'
  listen: 19999

mysql:
  host: '192.168.1.31:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'luban-demo'
  username: 'root'
  password: '123456'
