http:
  # debug release
  mode: 'debug'
  listen: 19999

mysql:
  host: 'localhost:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'luban-demo'
  username: 'root'
  password: 'd7131eeba69adaa0d6487bfddabd4b4b'


ldap:
  host: 172.16.10.134
  port: 389
  baseDn: "ou=infra,dc=xxxx,dc=com"
  # AD: manange@example.org
  bindUser: "cn=admin,dc=xxxx,dc=com"
  bindPass: "123456"
  # openldap: (&(uid=%s))
  # AD: (&(sAMAccountName=%s))
  #authFilter: "(&(uid=%s))"
  authFilter: "(&(objectClass=*)(cn=%s))"
  attributes:
    nickname: "displayName"
    email: "mail"
    phone: "mobile"
    uid: "uidNumber"
  coverAttributes: false
  autoRegist: true
  tls: false
  startTLS: false